Repository MmgTools/ParMmg, pull requests merged in 2024-08, with the labels that each got.

#113 Diagnose gatherv overflow
  src/mergemesh_pmmg.c
  src/parmmg.h
Labels: kind: bug, kind: enhancement, part: parmmg, part: MPI / HPC

#117 Fix gatherv overflow when the combined packed mesh size exceeds 2^31.
  src/mergemesh_pmmg.c
  src/mpi_pmmg.h
  src/mpipack_pmmg.c
  src/mpiunpack_pmmg.c
Labels: kind: bug

#119 Fix setting of maximal authorized memory
  CMakeLists.txt
  cmake/testing/pmmg_tests.cmake
  src/mergemesh_pmmg.c
  src/parmmg.c
  src/zaldy_pmmg.c
Labels: kind: bug, part: parmmg

#121 Update gfortran version after modification of Macos-12 runner.
  .github/workflows/main-job.yml
Labels: kind: ci-failure, priority: high

#122 Feature/fix duplication removal
  CMakeLists.txt
  src/communicators_pmmg.c
  src/coorcell_pmmg.c
Labels: kind: bug, part: parmmg

#112 API_DISTRIB_FACES prioritized over API_DISTRIB_NODES
  src/inout_pmmg.c
Labels: kind: bug, part: I/O, part: parmmg
